// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.journaldev.web.converter;

import com.journaldev.web.converter.EmployeeConverter;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect EmployeeConverter_Roo_Configurable {
    
    declare @type: EmployeeConverter: @Configurable;
    
}
