// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.journaldev.jpa.data;

import com.journaldev.jpa.data.Phone;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect Phone_Roo_Configurable {
    
    declare @type: Phone: @Configurable;
    
}
