// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.journaldev.web;

import com.journaldev.web.PhoneBean;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect PhoneBean_Roo_Configurable {
    
    declare @type: PhoneBean: @Configurable;
    
}
